# Generated by Django 4.1.7 on 2023-04-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='num_of_posts',
            field=models.IntegerField(default=0),
        ),
    ]
