# Generated by Django 4.1.7 on 2023-03-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0009_alter_animal_image_alter_tag_blue_alter_tag_green_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, default='https://source.unsplash.com/random/?cat', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='blue',
            field=models.IntegerField(default=224),
        ),
        migrations.AlterField(
            model_name='tag',
            name='green',
            field=models.IntegerField(default=128),
        ),
        migrations.AlterField(
            model_name='tag',
            name='red',
            field=models.IntegerField(default=200),
        ),
    ]
